name: test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        luaVersion: ["5.1.5", "5.2.4", "5.3.5", "5.4.2"]
        os: [macOs-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master
    - uses: ./
      with:
        lua-version: ${{ matrix.luaVersion }}

    - name: test lua
      run: |
        which lua
        lua -e "print(_VERSION)"
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        luaVersion: ["5.1.5", "5.2.4", "5.3.5", "5.4.2"]
        platform: [Win32, x64]
    steps:
    - uses: actions/checkout@master
    - uses: ./
      with:
        lua-version: ${{ matrix.luaVersion }}
        platform: ${{ matrix.platform }}
    - name: test lua
      run: |
        which lua
        lua -e "print(_VERSION)"
